import type { Rule } from './types';

/**
 * The rule catalogue.
 *
 * Each rule follows the documented schema (id, category, severity, description,
 * fix, impact, estimatedSavings?, documentation?) plus a `test` predicate that
 * returns TRUE when the page VIOLATES it. Rules are pure functions of
 * `PageFacts`, so the whole catalogue is unit-testable with fixtures and grows
 * without touching the engine.
 *
 * This is the starter set for the browserless analyzers (SEO, security, HTML,
 * assets, best practices). The platform's target of 500+ is reached by adding
 * entries here and, in the browser phase, rules over the Lighthouse and
 * axe-core output - the engine and the `Finding` shape do not change.
 */
export const RULES: Rule[] = [
  // ── SEO ──────────────────────────────────────────────────────────────────
  {
    id: 'seo-title-missing',
    category: 'seo',
    severity: 'serious',
    description: 'The page has no <title>.',
    fix: 'Add a unique, descriptive <title> of roughly 50–60 characters.',
    impact: 'The title is the primary label in search results and browser tabs.',
    documentation: 'https://developer.mozilla.org/docs/Web/HTML/Element/title',
    test: (f) => !f.title || f.title.length === 0,
  },
  {
    id: 'seo-title-length',
    category: 'seo',
    severity: 'minor',
    description: 'The <title> is too short or too long.',
    fix: 'Aim for 30–60 characters so it is not truncated in results.',
    impact: 'Over-long titles are cut off; over-short ones waste the slot.',
    test: (f) => f.titleLength > 0 && (f.titleLength < 15 || f.titleLength > 65),
  },
  {
    id: 'seo-meta-description-missing',
    category: 'seo',
    severity: 'moderate',
    description: 'The page has no meta description.',
    fix: 'Add a <meta name="description"> summarising the page in ~150 characters.',
    impact: 'Search engines fall back to scraping text, which reads poorly.',
    test: (f) => !f.metaDescription,
  },
  {
    id: 'seo-meta-description-length',
    category: 'seo',
    severity: 'minor',
    description: 'The meta description is outside the 70–160 character sweet spot.',
    fix: 'Rewrite it to roughly 150 characters.',
    impact: 'Descriptions outside this range get truncated or padded.',
    test: (f) => f.metaDescriptionLength > 0 && (f.metaDescriptionLength < 70 || f.metaDescriptionLength > 160),
  },
  {
    id: 'seo-canonical-missing',
    category: 'seo',
    severity: 'minor',
    description: 'No canonical URL is declared.',
    fix: 'Add <link rel="canonical"> pointing at the preferred URL.',
    impact: 'Duplicate URLs can split ranking signals without a canonical.',
    test: (f) => !f.canonical,
  },
  {
    id: 'seo-og-missing',
    category: 'seo',
    severity: 'minor',
    description: 'Open Graph tags are missing.',
    fix: 'Add og:title, og:description and og:image for rich social previews.',
    impact: 'Links shared to social platforms render as bare URLs.',
    test: (f) => Object.keys(f.openGraph).length === 0,
  },
  {
    id: 'seo-structured-data-missing',
    category: 'seo',
    severity: 'minor',
    description: 'No JSON-LD structured data was found.',
    fix: 'Add schema.org JSON-LD so search engines can build rich results.',
    impact: 'Structured data unlocks rich snippets and better understanding.',
    test: (f) => f.jsonLdBlocks === 0,
  },
  {
    id: 'seo-lang-missing',
    category: 'seo',
    severity: 'moderate',
    description: 'The <html> element has no lang attribute.',
    fix: 'Add lang="en" (or the page language) to the <html> tag.',
    impact: 'Language affects search, translation and screen-reader pronunciation.',
    test: (f) => !f.lang,
  },

  // ── HTML structure ────────────────────────────────────────────────────────
  {
    id: 'html-h1-missing',
    category: 'html',
    severity: 'moderate',
    description: 'The page has no <h1>.',
    fix: 'Give the page exactly one <h1> naming its main topic.',
    impact: 'The h1 anchors the document outline for readers and crawlers.',
    test: (f) => f.h1Count === 0,
  },
  {
    id: 'html-h1-multiple',
    category: 'html',
    severity: 'minor',
    description: 'The page has more than one <h1>.',
    fix: 'Keep a single <h1>; demote the rest to <h2>+.',
    impact: 'Multiple h1s blur the outline and the page’s primary subject.',
    test: (f) => f.h1Count > 1,
  },
  {
    id: 'html-heading-order',
    category: 'html',
    severity: 'moderate',
    description: 'Heading levels skip a step (e.g. h2 to h4).',
    fix: 'Use headings in order without jumping levels going down.',
    impact: 'Skipped levels break the outline assistive tech relies on.',
    test: (f) => !f.headingOrderOk,
  },
  {
    id: 'html-viewport-missing',
    category: 'html',
    severity: 'serious',
    description: 'No responsive viewport meta tag.',
    fix: 'Add <meta name="viewport" content="width=device-width, initial-scale=1">.',
    impact: 'Without it, mobile browsers render a zoomed-out desktop layout.',
    test: (f) => !f.viewport,
  },
  {
    id: 'html-charset-missing',
    category: 'html',
    severity: 'minor',
    description: 'No character encoding is declared.',
    fix: 'Add <meta charset="utf-8"> as the first thing in <head>.',
    impact: 'A missing charset can garble non-ASCII text.',
    test: (f) => !f.charset,
  },
  {
    id: 'html-favicon-missing',
    category: 'html',
    severity: 'info',
    description: 'No favicon is linked.',
    fix: 'Add a <link rel="icon"> so the tab and bookmarks have an icon.',
    impact: 'A missing favicon reads as unpolished in tabs and history.',
    test: (f) => !f.favicon,
  },

  // ── Accessibility (markup-level; deep audit comes with axe-core) ──────────
  {
    id: 'a11y-image-alt',
    category: 'accessibility',
    severity: 'serious',
    description: 'Some images have no alt attribute.',
    fix: 'Give every <img> an alt (empty alt="" for decorative images).',
    impact: 'Screen-reader users get no description of these images.',
    test: (f) => f.images.missingAlt > 0,
  },

  // ── Assets / performance hygiene ──────────────────────────────────────────
  {
    id: 'assets-render-blocking-scripts',
    category: 'assets',
    severity: 'serious',
    description: 'Render-blocking scripts are loaded in the document.',
    fix: 'Add async or defer, or move scripts to the end of <body>.',
    impact: 'Blocking scripts delay first paint and interactivity.',
    estimatedSavings: 'faster LCP / TTI',
    test: (f) => f.scripts.blocking > 0,
  },
  {
    id: 'assets-many-stylesheets',
    category: 'assets',
    severity: 'moderate',
    description: 'A large number of render-blocking stylesheets.',
    fix: 'Bundle CSS and inline the critical path; defer the rest.',
    impact: 'Each blocking stylesheet is a round trip before first paint.',
    test: (f) => f.stylesheets.blocking > 4,
  },
  {
    id: 'assets-image-dimensions',
    category: 'assets',
    severity: 'moderate',
    description: 'Images are missing explicit width and height.',
    fix: 'Set width and height (or aspect-ratio) so the browser reserves space.',
    impact: 'Missing dimensions cause layout shift (CLS) as images load.',
    estimatedSavings: 'lower CLS',
    test: (f) => f.images.total > 0 && f.images.withDimensions < f.images.total,
  },
  {
    id: 'assets-lazy-loading',
    category: 'assets',
    severity: 'minor',
    description: 'No images use native lazy-loading.',
    fix: 'Add loading="lazy" to below-the-fold images.',
    impact: 'Eagerly loading every image wastes bandwidth on unseen ones.',
    estimatedSavings: 'fewer bytes on load',
    test: (f) => f.images.total > 3 && f.images.lazy === 0,
  },
  {
    id: 'assets-html-weight',
    category: 'assets',
    severity: 'minor',
    description: 'The HTML document itself is unusually large.',
    fix: 'Trim inlined data and markup; paginate or stream long lists.',
    impact: 'A heavy document delays parsing and first paint.',
    estimatedSavings: 'faster parse',
    test: (f) => f.htmlBytes > 500 * 1024,
  },

  // ── Security ──────────────────────────────────────────────────────────────
  {
    id: 'sec-https',
    category: 'security',
    severity: 'critical',
    description: 'The page is not served over HTTPS.',
    fix: 'Serve the site over TLS and redirect http to https.',
    impact: 'Traffic can be read and tampered with in transit.',
    test: (f) => !f.security.https,
  },
  {
    id: 'sec-hsts',
    category: 'security',
    severity: 'moderate',
    description: 'No Strict-Transport-Security (HSTS) header.',
    fix: 'Send Strict-Transport-Security with a long max-age.',
    impact: 'Without HSTS, the first request can be downgraded to http.',
    test: (f) => f.security.https && !f.security.hsts,
  },
  {
    id: 'sec-csp',
    category: 'security',
    severity: 'serious',
    description: 'No Content-Security-Policy header.',
    fix: 'Add a Content-Security-Policy to restrict script and resource origins.',
    impact: 'A CSP is the strongest defence against cross-site scripting.',
    test: (f) => !f.security.csp,
  },
  {
    id: 'sec-x-content-type',
    category: 'security',
    severity: 'minor',
    description: 'No X-Content-Type-Options header.',
    fix: 'Send X-Content-Type-Options: nosniff.',
    impact: 'MIME sniffing can turn benign files into executable content.',
    test: (f) => !f.security.xContentTypeOptions,
  },
  {
    id: 'sec-x-frame-options',
    category: 'security',
    severity: 'moderate',
    description: 'No clickjacking protection (X-Frame-Options or frame-ancestors).',
    fix: 'Send X-Frame-Options: DENY or a CSP frame-ancestors directive.',
    impact: 'The page can be framed by an attacker for clickjacking.',
    test: (f) => !f.security.xFrameOptions && !f.security.csp,
  },
  {
    id: 'sec-referrer-policy',
    category: 'security',
    severity: 'minor',
    description: 'No Referrer-Policy header.',
    fix: 'Send Referrer-Policy: strict-origin-when-cross-origin.',
    impact: 'Full URLs may leak to third parties in the Referer header.',
    test: (f) => !f.security.referrerPolicy,
  },
  {
    id: 'sec-insecure-cookies',
    category: 'security',
    severity: 'serious',
    description: 'Cookies are set without Secure and HttpOnly flags.',
    fix: 'Mark cookies Secure and HttpOnly (and SameSite) unless JS needs them.',
    impact: 'Such cookies can be stolen over http or via cross-site scripting.',
    test: (f) => f.security.insecureCookies > 0,
  },

  // ── Best practices ────────────────────────────────────────────────────────
  {
    id: 'bp-status-not-ok',
    category: 'bestPractices',
    severity: 'serious',
    description: 'The final response was not a 200 OK.',
    fix: 'Ensure the scanned URL resolves to a successful response.',
    impact: 'Non-200 pages may be error or redirect pages, not real content.',
    test: (f) => f.status !== 200,
  },
  {
    id: 'bp-excessive-redirects',
    category: 'bestPractices',
    severity: 'minor',
    description: 'The URL went through multiple redirects before resolving.',
    fix: 'Point links and canonicals straight at the final URL.',
    impact: 'Each redirect adds a round trip before anything renders.',
    test: (f) => f.redirects.length > 1,
  },
];
