import type { ComponentType } from 'react';

/**
 * Live preview registry - slug → the real, running component.
 *
 * ─── Why these are hand-written, not eval'd from `code` ─────────────────────
 * Executing the registry's source strings at runtime would mean shipping a
 * transpiler to the browser and `eval`-ing code paths, which is both slow and
 * the exact shape of an XSS hole the moment anything user-authored (a CMS
 * submission) enters the pipeline. A preview is a separate, real implementation
 * of the same component - the code tab remains the copy-paste source of truth.
 *
 * The cost is that a preview can drift from its snippet. Keep them in step when
 * editing either; a preview that lies is worse than no preview.
 */
export interface PreviewModule {
  /** The rendered component. Takes no props - previews are self-contained. */
  Component: ComponentType;
  /**
   * Extra height hint in px when the default 12rem stage is too short.
   * The stage centres its child, so most components need nothing.
   */
  minHeight?: number;
}

/**
 * Lazily resolved so a detail page only loads the one preview it renders,
 * rather than every component in the library.
 */
export const PREVIEWS: Record<string, () => Promise<PreviewModule>> = {
  'about-stats': () =>
    import('./about-stats-preview').then((m) => ({ Component: m.default })),
  'about-story': () =>
    import('./about-story-preview').then((m) => ({ Component: m.default })),
  'about-team-grid': () =>
    import('./about-team-grid-preview').then((m) => ({ Component: m.default })),
  'about-timeline': () =>
    import('./about-timeline-preview').then((m) => ({ Component: m.default })),
  'about-values': () =>
    import('./about-values-preview').then((m) => ({ Component: m.default })),
  'accordion-bordered': () =>
    import('./accordion-bordered-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'accordion-faq-search': () =>
    import('./accordion-faq-search-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'accordion-filled': () =>
    import('./accordion-filled-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'accordion-icon-left': () =>
    import('./accordion-icon-left-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'accordion-multi-open': () =>
    import('./accordion-multi-open-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'accordion-native-details': () =>
    import('./accordion-native-details-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'accordion-nested': () =>
    import('./accordion-nested-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'accordion-plus-minus': () =>
    import('./accordion-plus-minus-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'accordion-separated': () =>
    import('./accordion-separated-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'alert-banner-top': () =>
    import('./alert-banner-top-preview').then((m) => ({ Component: m.default })),
  'alert-callout': () =>
    import('./alert-callout-preview').then((m) => ({ Component: m.default })),
  'alert-dismissible': () =>
    import('./alert-dismissible-preview').then((m) => ({ Component: m.default })),
  'alert-inline': () =>
    import('./alert-inline-preview').then((m) => ({ Component: m.default })),
  'alert-with-actions': () =>
    import('./alert-with-actions-preview').then((m) => ({ Component: m.default })),
  'blog-post-card': () =>
    import('./blog-post-card-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'carousel-autoplay': () =>
    import('./carousel-autoplay-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'carousel-basic': () =>
    import('./carousel-basic-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'carousel-fade': () =>
    import('./carousel-fade-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'carousel-multi-slide': () =>
    import('./carousel-multi-slide-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'carousel-thumbnails': () =>
    import('./carousel-thumbnails-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'checkbox-basic': () =>
    import('./checkbox-basic-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'checkbox-card': () =>
    import('./checkbox-card-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'checkbox-indeterminate': () =>
    import('./checkbox-indeterminate-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'checkbox-list-group': () =>
    import('./checkbox-list-group-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'checkbox-switch': () =>
    import('./checkbox-switch-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'comparison-before-after-cards': () =>
    import('./comparison-before-after-cards-preview').then((m) => ({ Component: m.default })),
  'comparison-feature-matrix': () =>
    import('./comparison-feature-matrix-preview').then((m) => ({ Component: m.default })),
  'comparison-image-slider': () =>
    import('./comparison-image-slider-preview').then((m) => ({ Component: m.default })),
  'comparison-table': () =>
    import('./comparison-table-preview').then((m) => ({ Component: m.default })),
  'comparison-two-column': () =>
    import('./comparison-two-column-preview').then((m) => ({ Component: m.default })),
  'copy-button': () =>
    import('./copy-button-preview').then((m) => ({ Component: m.default })),
  'destructive-button': () =>
    import('./destructive-button-preview').then((m) => ({ Component: m.default })),
  'dock-bottom-mobile-nav': () =>
    import('./dock-bottom-mobile-nav-preview').then((m) => ({ Component: m.default, minHeight: 272 })),
  'dock-floating-toolbar': () =>
    import('./dock-floating-toolbar-preview').then((m) => ({ Component: m.default, minHeight: 272 })),
  'dock-labeled-icons': () =>
    import('./dock-labeled-icons-preview').then((m) => ({ Component: m.default, minHeight: 272 })),
  'dock-macos-magnify': () =>
    import('./dock-macos-magnify-preview').then((m) => ({ Component: m.default, minHeight: 272 })),
  'dock-vertical-rail': () =>
    import('./dock-vertical-rail-preview').then((m) => ({ Component: m.default, minHeight: 304 })),
  'dropdown-basic': () =>
    import('./dropdown-basic-preview').then((m) => ({ Component: m.default })),
  'dropdown-grouped': () =>
    import('./dropdown-grouped-preview').then((m) => ({ Component: m.default })),
  'dropdown-nested': () =>
    import('./dropdown-nested-preview').then((m) => ({ Component: m.default })),
  'dropdown-profile': () =>
    import('./dropdown-profile-preview').then((m) => ({ Component: m.default })),
  'dropdown-with-icons': () =>
    import('./dropdown-with-icons-preview').then((m) => ({ Component: m.default })),
  'fab-basic': () =>
    import('./fab-basic-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'fab-extended': () =>
    import('./fab-extended-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'fab-scroll-to-top': () =>
    import('./fab-scroll-to-top-preview').then((m) => ({ Component: m.default, minHeight: 304 })),
  'fab-speed-dial': () =>
    import('./fab-speed-dial-preview').then((m) => ({ Component: m.default, minHeight: 336 })),
  'fab-with-tooltip': () =>
    import('./fab-with-tooltip-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'fade-in-on-scroll': () =>
    import('./fade-in-on-scroll-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'faq-accordion': () =>
    import('./faq-accordion-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'feature-card': () =>
    import('./feature-card-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'footer-minimal-legal': () =>
    import('./footer-minimal-legal-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'footer-multi-column': () =>
    import('./footer-multi-column-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'footer-newsletter': () =>
    import('./footer-newsletter-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'footer-simple': () =>
    import('./footer-simple-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'footer-social': () =>
    import('./footer-social-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'gallery-carousel-thumbs': () =>
    import('./gallery-carousel-thumbs-preview').then((m) => ({ Component: m.default })),
  'gallery-filterable': () =>
    import('./gallery-filterable-preview').then((m) => ({ Component: m.default })),
  'gallery-grid': () =>
    import('./gallery-grid-preview').then((m) => ({ Component: m.default })),
  'gallery-lightbox': () =>
    import('./gallery-lightbox-preview').then((m) => ({ Component: m.default, minHeight: 464 })),
  'gallery-masonry': () =>
    import('./gallery-masonry-preview').then((m) => ({ Component: m.default })),
  'ghost-button': () =>
    import('./ghost-button-preview').then((m) => ({ Component: m.default })),
  'gradient-glow-button': () =>
    import('./gradient-glow-button-preview').then((m) => ({ Component: m.default })),
  'hero-centered': () =>
    import('./hero-centered-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'hero-gradient-bg': () =>
    import('./hero-gradient-bg-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'hero-split-image': () =>
    import('./hero-split-image-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'hero-video-bg': () =>
    import('./hero-video-bg-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'hero-with-form': () =>
    import('./hero-with-form-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'horizontal-card': () =>
    import('./horizontal-card-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'icon-button': () =>
    import('./icon-button-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'image-overlay-card': () =>
    import('./image-overlay-card-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'input-basic': () =>
    import('./input-basic-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'input-floating-label': () =>
    import('./input-floating-label-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'input-with-addon': () =>
    import('./input-with-addon-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'input-with-error': () =>
    import('./input-with-error-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'input-with-icon': () =>
    import('./input-with-icon-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'loader-bar-indeterminate': () =>
    import('./loader-bar-indeterminate-preview').then((m) => ({ Component: m.default })),
  'loader-dots': () =>
    import('./loader-dots-preview').then((m) => ({ Component: m.default })),
  'loader-skeleton-card': () =>
    import('./loader-skeleton-card-preview').then((m) => ({ Component: m.default })),
  'loading-button': () =>
    import('./loading-button-preview').then((m) => ({ Component: m.default })),
  'modal-basic': () =>
    import('./modal-basic-preview').then((m) => ({ Component: m.default, minHeight: 432 })),
  'modal-confirm': () =>
    import('./modal-confirm-preview').then((m) => ({ Component: m.default, minHeight: 432 })),
  'modal-drawer-bottom': () =>
    import('./modal-drawer-bottom-preview').then((m) => ({ Component: m.default, minHeight: 432 })),
  'modal-form': () =>
    import('./modal-form-preview').then((m) => ({ Component: m.default, minHeight: 496 })),
  'modal-fullscreen': () =>
    import('./modal-fullscreen-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'multiselect-checkbox-list': () =>
    import('./multiselect-checkbox-list-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-chips': () =>
    import('./multiselect-chips-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-grouped': () =>
    import('./multiselect-grouped-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-inline-tags': () =>
    import('./multiselect-inline-tags-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-limit': () =>
    import('./multiselect-limit-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-search-async': () =>
    import('./multiselect-search-async-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-search-avatars': () =>
    import('./multiselect-search-avatars-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-search-basic': () =>
    import('./multiselect-search-basic-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-search-create': () =>
    import('./multiselect-search-create-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'multiselect-search-keyboard': () =>
    import('./multiselect-search-keyboard-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'navbar-centered-logo': () =>
    import('./navbar-centered-logo-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'navbar-mobile-drawer': () =>
    import('./navbar-mobile-drawer-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'navbar-simple': () =>
    import('./navbar-simple-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'navbar-sticky-blur': () =>
    import('./navbar-sticky-blur-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'navbar-with-dropdown': () =>
    import('./navbar-with-dropdown-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'newsletter-card': () =>
    import('./newsletter-card-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'newsletter-footer-bar': () =>
    import('./newsletter-footer-bar-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'newsletter-inline': () =>
    import('./newsletter-inline-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'newsletter-modal': () =>
    import('./newsletter-modal-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'newsletter-split': () =>
    import('./newsletter-split-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'notification-badge-bell': () =>
    import('./notification-badge-bell-preview').then((m) => ({ Component: m.default })),
  'notification-card': () =>
    import('./notification-card-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'notification-inline-banner': () =>
    import('./notification-inline-banner-preview').then((m) => ({ Component: m.default })),
  'notification-list-panel': () =>
    import('./notification-list-panel-preview').then((m) => ({ Component: m.default })),
  'outline-button': () =>
    import('./outline-button-preview').then((m) => ({ Component: m.default })),
  'pagination-infinite-sentinel': () =>
    import('./pagination-infinite-sentinel-preview').then((m) => ({ Component: m.default })),
  'pagination-load-more': () =>
    import('./pagination-load-more-preview').then((m) => ({ Component: m.default })),
  'pagination-numbered': () =>
    import('./pagination-numbered-preview').then((m) => ({ Component: m.default })),
  'pagination-prev-next': () =>
    import('./pagination-prev-next-preview').then((m) => ({ Component: m.default })),
  'pagination-with-page-size': () =>
    import('./pagination-with-page-size-preview').then((m) => ({ Component: m.default })),
  'pill-button': () =>
    import('./pill-button-preview').then((m) => ({ Component: m.default })),
  'popover-arrow': () =>
    import('./popover-arrow-preview').then((m) => ({ Component: m.default })),
  'popover-basic': () =>
    import('./popover-basic-preview').then((m) => ({ Component: m.default })),
  'popover-menu': () =>
    import('./popover-menu-preview').then((m) => ({ Component: m.default })),
  'popover-rich-content': () =>
    import('./popover-rich-content-preview').then((m) => ({ Component: m.default })),
  'popover-tooltip': () =>
    import('./popover-tooltip-preview').then((m) => ({ Component: m.default })),
  'pricing-card': () =>
    import('./pricing-card-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'pricing-comparison-grid': () =>
    import('./pricing-comparison-grid-preview').then((m) => ({ Component: m.default })),
  'pricing-single-card': () =>
    import('./pricing-single-card-preview').then((m) => ({ Component: m.default })),
  'pricing-three-tier': () =>
    import('./pricing-three-tier-preview').then((m) => ({ Component: m.default })),
  'pricing-toggle-billing': () =>
    import('./pricing-toggle-billing-preview').then((m) => ({ Component: m.default })),
  'pricing-usage-slider': () =>
    import('./pricing-usage-slider-preview').then((m) => ({ Component: m.default })),
  'product-card': () =>
    import('./product-card-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'profile-card': () =>
    import('./profile-card-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'progress-bar': () =>
    import('./progress-bar-preview').then((m) => ({ Component: m.default })),
  'radio-basic': () =>
    import('./radio-basic-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'radio-button-group': () =>
    import('./radio-button-group-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'radio-card': () =>
    import('./radio-card-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'radio-inline': () =>
    import('./radio-inline-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'radio-with-description': () =>
    import('./radio-with-description-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'select-custom': () =>
    import('./select-custom-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'select-grouped': () =>
    import('./select-grouped-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'select-native': () =>
    import('./select-native-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'select-with-error': () =>
    import('./select-with-error-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'select-with-icons': () =>
    import('./select-with-icons-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'service-detail-faq': () =>
    import('./service-detail-faq-preview').then((m) => ({ Component: m.default })),
  'service-detail-features': () =>
    import('./service-detail-features-preview').then((m) => ({ Component: m.default })),
  'service-detail-hero': () =>
    import('./service-detail-hero-preview').then((m) => ({ Component: m.default })),
  'service-detail-pricing-cta': () =>
    import('./service-detail-pricing-cta-preview').then((m) => ({ Component: m.default })),
  'service-detail-process': () =>
    import('./service-detail-process-preview').then((m) => ({ Component: m.default })),
  'services-alternating': () =>
    import('./services-alternating-preview').then((m) => ({ Component: m.default })),
  'services-cards-hover': () =>
    import('./services-cards-hover-preview').then((m) => ({ Component: m.default })),
  'services-grid': () =>
    import('./services-grid-preview').then((m) => ({ Component: m.default })),
  'services-icon-list': () =>
    import('./services-icon-list-preview').then((m) => ({ Component: m.default })),
  'services-tabbed': () =>
    import('./services-tabbed-preview').then((m) => ({ Component: m.default })),
  'sidebar-basic': () =>
    import('./sidebar-basic-preview').then((m) => ({ Component: m.default, minHeight: 304 })),
  'sidebar-collapsible': () =>
    import('./sidebar-collapsible-preview').then((m) => ({ Component: m.default, minHeight: 304 })),
  'sidebar-icon-rail': () =>
    import('./sidebar-icon-rail-preview').then((m) => ({ Component: m.default, minHeight: 304 })),
  'sidebar-mobile-drawer': () =>
    import('./sidebar-mobile-drawer-preview').then((m) => ({ Component: m.default, minHeight: 336 })),
  'sidebar-nested-groups': () =>
    import('./sidebar-nested-groups-preview').then((m) => ({ Component: m.default, minHeight: 368 })),
  'skeleton-loader': () =>
    import('./skeleton-loader-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'social-login-button': () =>
    import('./social-login-button-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'spinner-ring': () =>
    import('./spinner-ring-preview').then((m) => ({ Component: m.default })),
  'split-button': () =>
    import('./split-button-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'stat-card': () =>
    import('./stat-card-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'tabs-boxed': () =>
    import('./tabs-boxed-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'tabs-pills': () =>
    import('./tabs-pills-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'tabs-underline': () =>
    import('./tabs-underline-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'tabs-vertical': () =>
    import('./tabs-vertical-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'tabs-with-icons': () =>
    import('./tabs-with-icons-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'testimonial-card': () =>
    import('./testimonial-card-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'textarea-autosize': () =>
    import('./textarea-autosize-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'textarea-basic': () =>
    import('./textarea-basic-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'textarea-resizable': () =>
    import('./textarea-resizable-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'textarea-with-counter': () =>
    import('./textarea-with-counter-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'textarea-with-toolbar': () =>
    import('./textarea-with-toolbar-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'toast-basic': () =>
    import('./toast-basic-preview').then((m) => ({ Component: m.default, minHeight: 208 })),
  'toast-stack': () =>
    import('./toast-stack-preview').then((m) => ({ Component: m.default, minHeight: 272 })),
  'avatar-badge-count': () =>
    import('./avatar-badge-count-preview').then((m) => ({ Component: m.default })),
  'avatar-group-stack': () =>
    import('./avatar-group-stack-preview').then((m) => ({ Component: m.default })),
  'avatar-initials-basic': () =>
    import('./avatar-initials-basic-preview').then((m) => ({ Component: m.default })),
  'avatar-sizes-scale': () =>
    import('./avatar-sizes-scale-preview').then((m) => ({ Component: m.default })),
  'avatar-squared': () =>
    import('./avatar-squared-preview').then((m) => ({ Component: m.default })),
  'avatar-status-dot': () =>
    import('./avatar-status-dot-preview').then((m) => ({ Component: m.default })),
  'badge-corner-notification': () =>
    import('./badge-corner-notification-preview').then((m) => ({ Component: m.default })),
  'badge-counter': () =>
    import('./badge-counter-preview').then((m) => ({ Component: m.default })),
  'badge-gradient-shine': () =>
    import('./badge-gradient-shine-preview').then((m) => ({ Component: m.default })),
  'badge-outline-set': () =>
    import('./badge-outline-set-preview').then((m) => ({ Component: m.default })),
  'badge-pill-soft': () =>
    import('./badge-pill-soft-preview').then((m) => ({ Component: m.default })),
  'badge-removable': () =>
    import('./badge-removable-preview').then((m) => ({ Component: m.default })),
  'badge-ribbon-corner': () =>
    import('./badge-ribbon-corner-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'badge-status-set': () =>
    import('./badge-status-set-preview').then((m) => ({ Component: m.default })),
  'badge-verified-check': () =>
    import('./badge-verified-check-preview').then((m) => ({ Component: m.default })),
  'badge-with-icon': () =>
    import('./badge-with-icon-preview').then((m) => ({ Component: m.default })),
  'file-upload-avatar': () =>
    import('./file-upload-avatar-preview').then((m) => ({ Component: m.default })),
  'file-upload-button-compact': () =>
    import('./file-upload-button-compact-preview').then((m) => ({ Component: m.default })),
  'file-upload-drag-overlay': () =>
    import('./file-upload-drag-overlay-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'file-upload-dropzone-basic': () =>
    import('./file-upload-dropzone-basic-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'file-upload-paste': () =>
    import('./file-upload-paste-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'file-upload-queue-retry': () =>
    import('./file-upload-queue-retry-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'file-upload-validation-hints': () =>
    import('./file-upload-validation-hints-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'gradient-animated-blobs': () =>
    import('./gradient-animated-blobs-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'gradient-mesh-background': () =>
    import('./gradient-mesh-background-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'progress-circular-ring': () =>
    import('./progress-circular-ring-preview').then((m) => ({ Component: m.default })),
  'progress-linear-label': () =>
    import('./progress-linear-label-preview').then((m) => ({ Component: m.default })),
  'search-command-modal': () =>
    import('./search-command-modal-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'search-debounced-async': () =>
    import('./search-debounced-async-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'search-fullpage-overlay': () =>
    import('./search-fullpage-overlay-preview').then((m) => ({ Component: m.default })),
  'search-hero-suggestions': () =>
    import('./search-hero-suggestions-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'search-navbar-expand': () =>
    import('./search-navbar-expand-preview').then((m) => ({ Component: m.default })),
  'search-recent-history': () =>
    import('./search-recent-history-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'search-results-highlight': () =>
    import('./search-results-highlight-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'search-scoped-tabs': () =>
    import('./search-scoped-tabs-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'search-with-filters': () =>
    import('./search-with-filters-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'testimonial-carousel': () =>
    import('./testimonial-carousel-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'testimonial-grid-three': () =>
    import('./testimonial-grid-three-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'testimonial-masonry-wall': () =>
    import('./testimonial-masonry-wall-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'testimonial-spotlight-single': () =>
    import('./testimonial-spotlight-single-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'footer-accordion-mobile': () =>
    import('./footer-accordion-mobile-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'footer-app-badges': () =>
    import('./footer-app-badges-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'footer-centered-logo': () =>
    import('./footer-centered-logo-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'footer-contact-split': () =>
    import('./footer-contact-split-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'footer-cta-banner': () =>
    import('./footer-cta-banner-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'footer-dark-gradient-brand': () =>
    import('./footer-dark-gradient-brand-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'footer-language-currency': () =>
    import('./footer-language-currency-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'footer-mega-links': () =>
    import('./footer-mega-links-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'footer-minimal-floating': () =>
    import('./footer-minimal-floating-preview').then((m) => ({ Component: m.default })),
  'footer-stats-strip': () =>
    import('./footer-stats-strip-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'hero-animated-words': () =>
    import('./hero-animated-words-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'hero-announcement-banner': () =>
    import('./hero-announcement-banner-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'hero-app-screenshot': () =>
    import('./hero-app-screenshot-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'hero-bento-grid': () =>
    import('./hero-bento-grid-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'hero-cards-collage': () =>
    import('./hero-cards-collage-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'hero-dark-glow': () =>
    import('./hero-dark-glow-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'hero-logos-strip': () =>
    import('./hero-logos-strip-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'hero-search': () =>
    import('./hero-search-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'hero-split-checklist': () =>
    import('./hero-split-checklist-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'hero-stats': () =>
    import('./hero-stats-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'marquee-announcement-bar': () =>
    import('./marquee-announcement-bar-preview').then((m) => ({ Component: m.default })),
  'marquee-dual-row-opposite': () =>
    import('./marquee-dual-row-opposite-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'marquee-gradient-mask-edges': () =>
    import('./marquee-gradient-mask-edges-preview').then((m) => ({ Component: m.default })),
  'marquee-image-tiles': () =>
    import('./marquee-image-tiles-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'marquee-logos-strip': () =>
    import('./marquee-logos-strip-preview').then((m) => ({ Component: m.default })),
  'marquee-pause-on-hover': () =>
    import('./marquee-pause-on-hover-preview').then((m) => ({ Component: m.default })),
  'marquee-skills-chips': () =>
    import('./marquee-skills-chips-preview').then((m) => ({ Component: m.default })),
  'marquee-testimonials-strip': () =>
    import('./marquee-testimonials-strip-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'marquee-text-ticker': () =>
    import('./marquee-text-ticker-preview').then((m) => ({ Component: m.default })),
  'marquee-vertical-scroll': () =>
    import('./marquee-vertical-scroll-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'navbar-announcement-bar': () =>
    import('./navbar-announcement-bar-preview').then((m) => ({ Component: m.default })),
  'navbar-double-decker': () =>
    import('./navbar-double-decker-preview').then((m) => ({ Component: m.default })),
  'navbar-ecommerce-icons': () =>
    import('./navbar-ecommerce-icons-preview').then((m) => ({ Component: m.default })),
  'navbar-mega-menu': () =>
    import('./navbar-mega-menu-preview').then((m) => ({ Component: m.default })),
  'navbar-pill-links': () =>
    import('./navbar-pill-links-preview').then((m) => ({ Component: m.default })),
  'navbar-split-actions': () =>
    import('./navbar-split-actions-preview').then((m) => ({ Component: m.default })),
  'navbar-tabs-subnav': () =>
    import('./navbar-tabs-subnav-preview').then((m) => ({ Component: m.default })),
  'navbar-transparent-overlay': () =>
    import('./navbar-transparent-overlay-preview').then((m) => ({ Component: m.default, minHeight: 288 })),
  'navbar-underline-indicator': () =>
    import('./navbar-underline-indicator-preview').then((m) => ({ Component: m.default })),
  'navbar-with-search': () =>
    import('./navbar-with-search-preview').then((m) => ({ Component: m.default })),
  'testimonial-avatar-strip': () =>
    import('./testimonial-avatar-strip-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'testimonial-minimal-serif': () =>
    import('./testimonial-minimal-serif-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'testimonial-rating-cards': () =>
    import('./testimonial-rating-cards-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'testimonial-split-featured': () =>
    import('./testimonial-split-featured-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'testimonial-video-thumb': () =>
    import('./testimonial-video-thumb-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'testimonial-with-logos': () =>
    import('./testimonial-with-logos-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'timeline-activity-feed': () =>
    import('./timeline-activity-feed-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'timeline-alternating': () =>
    import('./timeline-alternating-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'timeline-changelog': () =>
    import('./timeline-changelog-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'timeline-compact-dense': () =>
    import('./timeline-compact-dense-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'timeline-horizontal-scroll': () =>
    import('./timeline-horizontal-scroll-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'timeline-milestones-cards': () =>
    import('./timeline-milestones-cards-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'timeline-progress-line': () =>
    import('./timeline-progress-line-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'timeline-roadmap': () =>
    import('./timeline-roadmap-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'timeline-vertical-basic': () =>
    import('./timeline-vertical-basic-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'timeline-year-grouped': () =>
    import('./timeline-year-grouped-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'avatar-menu-trigger': () =>
    import('./avatar-menu-trigger-preview').then((m) => ({ Component: m.default })),
  'avatar-ring-story': () =>
    import('./avatar-ring-story-preview').then((m) => ({ Component: m.default })),
  'avatar-skeleton': () =>
    import('./avatar-skeleton-preview').then((m) => ({ Component: m.default })),
  'avatar-with-name-role': () =>
    import('./avatar-with-name-role-preview').then((m) => ({ Component: m.default })),
  'calendar-availability-slots': () =>
    import('./calendar-availability-slots-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'calendar-day-schedule': () =>
    import('./calendar-day-schedule-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'calendar-dual-month': () =>
    import('./calendar-dual-month-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'calendar-events-month': () =>
    import('./calendar-events-month-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'calendar-heatmap-year': () =>
    import('./calendar-heatmap-year-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'calendar-mini-compact': () =>
    import('./calendar-mini-compact-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'calendar-month-grid': () =>
    import('./calendar-month-grid-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'calendar-upcoming-list': () =>
    import('./calendar-upcoming-list-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'calendar-week-strip': () =>
    import('./calendar-week-strip-preview').then((m) => ({ Component: m.default })),
  'calendar-year-overview': () =>
    import('./calendar-year-overview-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'cursor-crosshair-precision': () =>
    import('./cursor-crosshair-precision-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-custom-svg': () =>
    import('./cursor-custom-svg-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-dot-follower': () =>
    import('./cursor-dot-follower-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-gradient-blob-follow': () =>
    import('./cursor-gradient-blob-follow-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-image-peek': () =>
    import('./cursor-image-peek-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-magnetic-button': () =>
    import('./cursor-magnetic-button-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-ring-lag-follower': () =>
    import('./cursor-ring-lag-follower-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-spotlight-reveal': () =>
    import('./cursor-spotlight-reveal-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-text-zoom-hover': () =>
    import('./cursor-text-zoom-hover-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cursor-trail-particles': () =>
    import('./cursor-trail-particles-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'gradient-aurora': () =>
    import('./gradient-aurora-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'gradient-border-card': () =>
    import('./gradient-border-card-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'gradient-button-set': () =>
    import('./gradient-button-set-preview').then((m) => ({ Component: m.default })),
  'gradient-conic-ring': () =>
    import('./gradient-conic-ring-preview').then((m) => ({ Component: m.default })),
  'gradient-noise-overlay': () =>
    import('./gradient-noise-overlay-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'gradient-radial-spotlight': () =>
    import('./gradient-radial-spotlight-preview').then((m) => ({ Component: m.default })),
  'gradient-section-divider': () =>
    import('./gradient-section-divider-preview').then((m) => ({ Component: m.default })),
  'gradient-text': () =>
    import('./gradient-text-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'map-contact-split': () =>
    import('./map-contact-split-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'map-coverage-stats': () =>
    import('./map-coverage-stats-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'map-dark-glow': () =>
    import('./map-dark-glow-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'map-embed-responsive': () =>
    import('./map-embed-responsive-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'map-office-locations': () =>
    import('./map-office-locations-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'map-pin-popover': () =>
    import('./map-pin-popover-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'map-region-selector': () =>
    import('./map-region-selector-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'map-route-steps': () =>
    import('./map-route-steps-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'map-store-locator-list': () =>
    import('./map-store-locator-list-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'map-world-dotted': () =>
    import('./map-world-dotted-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'stepper-checkout': () =>
    import('./stepper-checkout-preview').then((m) => ({ Component: m.default })),
  'stepper-clickable-navigation': () =>
    import('./stepper-clickable-navigation-preview').then((m) => ({ Component: m.default })),
  'stepper-dots-compact': () =>
    import('./stepper-dots-compact-preview').then((m) => ({ Component: m.default })),
  'stepper-horizontal-numbered': () =>
    import('./stepper-horizontal-numbered-preview').then((m) => ({ Component: m.default })),
  'stepper-icons': () =>
    import('./stepper-icons-preview').then((m) => ({ Component: m.default })),
  'stepper-progress-fraction': () =>
    import('./stepper-progress-fraction-preview').then((m) => ({ Component: m.default })),
  'stepper-segmented-bar': () =>
    import('./stepper-segmented-bar-preview').then((m) => ({ Component: m.default })),
  'stepper-status-mixed': () =>
    import('./stepper-status-mixed-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'stepper-vertical-detailed': () =>
    import('./stepper-vertical-detailed-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'stepper-wizard-interactive': () =>
    import('./stepper-wizard-interactive-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'tooltip-basic': () =>
    import('./tooltip-basic-preview').then((m) => ({ Component: m.default })),
  'tooltip-click-pin': () =>
    import('./tooltip-click-pin-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'tooltip-delay-group': () =>
    import('./tooltip-delay-group-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'tooltip-follow-cursor': () =>
    import('./tooltip-follow-cursor-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'tooltip-icon-help': () =>
    import('./tooltip-icon-help-preview').then((m) => ({ Component: m.default })),
  'tooltip-kbd-shortcut': () =>
    import('./tooltip-kbd-shortcut-preview').then((m) => ({ Component: m.default })),
  'tooltip-positions': () =>
    import('./tooltip-positions-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'tooltip-rich': () =>
    import('./tooltip-rich-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'tooltip-status-bar': () =>
    import('./tooltip-status-bar-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'tooltip-truncation': () =>
    import('./tooltip-truncation-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'date-picker-birthday': () =>
    import('./date-picker-birthday-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'date-picker-dropdown-selects': () =>
    import('./date-picker-dropdown-selects-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'date-picker-inline-calendar': () =>
    import('./date-picker-inline-calendar-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'date-picker-input-masked': () =>
    import('./date-picker-input-masked-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'date-picker-input-popover': () =>
    import('./date-picker-input-popover-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'date-picker-min-max-bounds': () =>
    import('./date-picker-min-max-bounds-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'date-picker-range-dual-month': () =>
    import('./date-picker-range-dual-month-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'date-picker-range-single-month': () =>
    import('./date-picker-range-single-month-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'date-picker-week-picker': () =>
    import('./date-picker-week-picker-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'date-picker-with-presets': () =>
    import('./date-picker-with-presets-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'file-tree-breadcrumb-sync': () =>
    import('./file-tree-breadcrumb-sync-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'file-tree-checkbox-select': () =>
    import('./file-tree-checkbox-select-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'file-tree-code-project': () =>
    import('./file-tree-code-project-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'file-tree-collapsible-basic': () =>
    import('./file-tree-collapsible-basic-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'file-tree-context-actions': () =>
    import('./file-tree-context-actions-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'file-tree-drag-handle-visual': () =>
    import('./file-tree-drag-handle-visual-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'file-tree-file-size-meta': () =>
    import('./file-tree-file-size-meta-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'file-tree-file-type-icons': () =>
    import('./file-tree-file-type-icons-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'file-tree-git-status': () =>
    import('./file-tree-git-status-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'file-tree-search-filter': () =>
    import('./file-tree-search-filter-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'menu-account-menu': () =>
    import('./menu-account-menu-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'menu-context-right-click': () =>
    import('./menu-context-right-click-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'menu-filter-checkbox-menu': () =>
    import('./menu-filter-checkbox-menu-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'menu-icon-grid-launcher': () =>
    import('./menu-icon-grid-launcher-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'menu-kebab-row-actions': () =>
    import('./menu-kebab-row-actions-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'menu-keyboard-full': () =>
    import('./menu-keyboard-full-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'menu-menubar-desktop': () =>
    import('./menu-menubar-desktop-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'menu-mobile-bottom-sheet': () =>
    import('./menu-mobile-bottom-sheet-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'menu-nested-submenu': () =>
    import('./menu-nested-submenu-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'menu-pinnable-favorites': () =>
    import('./menu-pinnable-favorites-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'progress-goal-card': () =>
    import('./progress-goal-card-preview').then((m) => ({ Component: m.default })),
  'progress-indeterminate-thin': () =>
    import('./progress-indeterminate-thin-preview').then((m) => ({ Component: m.default })),
  'progress-mini-inline': () =>
    import('./progress-mini-inline-preview').then((m) => ({ Component: m.default })),
  'progress-multi-stacked': () =>
    import('./progress-multi-stacked-preview').then((m) => ({ Component: m.default })),
  'progress-radial-dashboard': () =>
    import('./progress-radial-dashboard-preview').then((m) => ({ Component: m.default })),
  'progress-segmented': () =>
    import('./progress-segmented-preview').then((m) => ({ Component: m.default })),
  'progress-steps-checklist': () =>
    import('./progress-steps-checklist-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'progress-striped-animated': () =>
    import('./progress-striped-animated-preview').then((m) => ({ Component: m.default })),
  'tag-autocomplete': () =>
    import('./tag-autocomplete-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'tag-colored-categories': () =>
    import('./tag-colored-categories-preview').then((m) => ({ Component: m.default })),
  'tag-editable': () =>
    import('./tag-editable-preview').then((m) => ({ Component: m.default })),
  'tag-filter-toggle': () =>
    import('./tag-filter-toggle-preview').then((m) => ({ Component: m.default })),
  'tag-input-chips': () =>
    import('./tag-input-chips-preview').then((m) => ({ Component: m.default })),
  'tag-overflow-counter': () =>
    import('./tag-overflow-counter-preview').then((m) => ({ Component: m.default })),
  'tag-removable-list': () =>
    import('./tag-removable-list-preview').then((m) => ({ Component: m.default })),
  'tag-selectable-grid': () =>
    import('./tag-selectable-grid-preview').then((m) => ({ Component: m.default })),
  'tag-size-variants': () =>
    import('./tag-size-variants-preview').then((m) => ({ Component: m.default })),
  'tag-with-icons': () =>
    import('./tag-with-icons-preview').then((m) => ({ Component: m.default })),
  'time-picker-12h-24h-toggle': () =>
    import('./time-picker-12h-24h-toggle-preview').then((m) => ({ Component: m.default })),
  'time-picker-analog-dial': () =>
    import('./time-picker-analog-dial-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'time-picker-dropdown-intervals': () =>
    import('./time-picker-dropdown-intervals-preview').then((m) => ({ Component: m.default })),
  'time-picker-duration': () =>
    import('./time-picker-duration-preview').then((m) => ({ Component: m.default })),
  'time-picker-keyboard-typed': () =>
    import('./time-picker-keyboard-typed-preview').then((m) => ({ Component: m.default })),
  'time-picker-range-start-end': () =>
    import('./time-picker-range-start-end-preview').then((m) => ({ Component: m.default })),
  'time-picker-scroll-columns': () =>
    import('./time-picker-scroll-columns-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'time-picker-slots-grid': () =>
    import('./time-picker-slots-grid-preview').then((m) => ({ Component: m.default })),
  'time-picker-steppers-input': () =>
    import('./time-picker-steppers-input-preview').then((m) => ({ Component: m.default })),
  'time-picker-timezone-select': () =>
    import('./time-picker-timezone-select-preview').then((m) => ({ Component: m.default })),
  'color-picker-alpha-slider': () =>
    import('./color-picker-alpha-slider-preview').then((m) => ({ Component: m.default })),
  'color-picker-contrast-checker': () =>
    import('./color-picker-contrast-checker-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'color-picker-gradient-builder': () =>
    import('./color-picker-gradient-builder-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'color-picker-hex-input': () =>
    import('./color-picker-hex-input-preview').then((m) => ({ Component: m.default })),
  'color-picker-hsl-sliders': () =>
    import('./color-picker-hsl-sliders-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'color-picker-hue-slider': () =>
    import('./color-picker-hue-slider-preview').then((m) => ({ Component: m.default })),
  'color-picker-palette-generator': () =>
    import('./color-picker-palette-generator-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'color-picker-recent-colors': () =>
    import('./color-picker-recent-colors-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'color-picker-saturation-pane': () =>
    import('./color-picker-saturation-pane-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'color-picker-swatch-grid': () =>
    import('./color-picker-swatch-grid-preview').then((m) => ({ Component: m.default })),
  'file-upload-image-grid-preview': () =>
    import('./file-upload-image-grid-preview-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'file-upload-multi-list-progress': () =>
    import('./file-upload-multi-list-progress-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'file-upload-split-url-tab': () =>
    import('./file-upload-split-url-tab-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'list-avatar-actions': () =>
    import('./list-avatar-actions-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'list-divided-basic': () =>
    import('./list-divided-basic-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'list-expandable-rows': () =>
    import('./list-expandable-rows-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'list-grouped-sticky-headers': () =>
    import('./list-grouped-sticky-headers-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'list-inbox-two-line': () =>
    import('./list-inbox-two-line-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'list-keyboard-move': () =>
    import('./list-keyboard-move-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'list-media-thumbnail': () =>
    import('./list-media-thumbnail-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'list-numbered-ranking': () =>
    import('./list-numbered-ranking-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'list-selectable-checkbox': () =>
    import('./list-selectable-checkbox-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'list-stats-trailing': () =>
    import('./list-stats-trailing-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'search-inline-table-filter': () =>
    import('./search-inline-table-filter-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'toggle-button-group-multi': () =>
    import('./toggle-button-group-multi-preview').then((m) => ({ Component: m.default })),
  'toggle-card-select': () =>
    import('./toggle-card-select-preview').then((m) => ({ Component: m.default })),
  'toggle-collapse-disclosure': () =>
    import('./toggle-collapse-disclosure-preview').then((m) => ({ Component: m.default })),
  'toggle-pill-single': () =>
    import('./toggle-pill-single-preview').then((m) => ({ Component: m.default })),
  'toggle-row-settings': () =>
    import('./toggle-row-settings-preview').then((m) => ({ Component: m.default })),
  'toggle-segmented-control': () =>
    import('./toggle-segmented-control-preview').then((m) => ({ Component: m.default })),
  'toggle-switch-async': () =>
    import('./toggle-switch-async-preview').then((m) => ({ Component: m.default })),
  'toggle-switch-basic': () =>
    import('./toggle-switch-basic-preview').then((m) => ({ Component: m.default })),
  'toggle-switch-icons': () =>
    import('./toggle-switch-icons-preview').then((m) => ({ Component: m.default })),
  'toggle-switch-labeled': () =>
    import('./toggle-switch-labeled-preview').then((m) => ({ Component: m.default })),
  'count-up-number': () =>
    import('./count-up-number-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'scroll-progress-bar': () =>
    import('./scroll-progress-bar-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'stagger-reveal-grid': () =>
    import('./stagger-reveal-grid-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'tour-coach-mark-spotlight': () =>
    import('./tour-coach-mark-spotlight-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'tour-feature-announcement-modal': () =>
    import('./tour-feature-announcement-modal-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'tour-hotspot-beacons': () =>
    import('./tour-hotspot-beacons-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'tour-onboarding-checklist': () =>
    import('./tour-onboarding-checklist-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'tour-step-tooltip-sequence': () =>
    import('./tour-step-tooltip-sequence-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'typewriter-text': () =>
    import('./typewriter-text-preview').then((m) => ({ Component: m.default })),
  'cta-app-download': () =>
    import('./cta-app-download-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'cta-card-floating': () =>
    import('./cta-card-floating-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'cta-centered-simple': () =>
    import('./cta-centered-simple-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'cta-dark-glow': () =>
    import('./cta-dark-glow-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'cta-full-bleed-pattern': () =>
    import('./cta-full-bleed-pattern-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'cta-gradient-banner': () =>
    import('./cta-gradient-banner-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cta-split-image': () =>
    import('./cta-split-image-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'cta-stats-band': () =>
    import('./cta-stats-band-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'cta-two-button': () =>
    import('./cta-two-button-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'cta-with-email-capture': () =>
    import('./cta-with-email-capture-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'signin-boxed-logo': () =>
    import('./signin-boxed-logo-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'signin-centered-card': () =>
    import('./signin-centered-card-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'signin-gradient-side': () =>
    import('./signin-gradient-side-preview').then((m) => ({ Component: m.default, minHeight: 500 })),
  'signin-inline-error': () =>
    import('./signin-inline-error-preview').then((m) => ({ Component: m.default, minHeight: 500 })),
  'signin-magic-link': () =>
    import('./signin-magic-link-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'signin-minimal': () =>
    import('./signin-minimal-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'signin-remember-forgot': () =>
    import('./signin-remember-forgot-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'signin-social-buttons': () =>
    import('./signin-social-buttons-preview').then((m) => ({ Component: m.default, minHeight: 540 })),
  'signin-split-image': () =>
    import('./signin-split-image-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'signin-with-2fa-code': () =>
    import('./signin-with-2fa-code-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'signup-boxed-logo': () =>
    import('./signup-boxed-logo-preview').then((m) => ({ Component: m.default, minHeight: 470 })),
  'signup-centered-card': () =>
    import('./signup-centered-card-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'signup-gradient-side': () =>
    import('./signup-gradient-side-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'signup-invite-code': () =>
    import('./signup-invite-code-preview').then((m) => ({ Component: m.default, minHeight: 470 })),
  'signup-minimal-email-only': () =>
    import('./signup-minimal-email-only-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'signup-multi-step': () =>
    import('./signup-multi-step-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'signup-password-strength': () =>
    import('./signup-password-strength-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'signup-social-first': () =>
    import('./signup-social-first-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'signup-split-benefits': () =>
    import('./signup-split-benefits-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'signup-with-terms-consent': () =>
    import('./signup-with-terms-consent-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'stats-big-number-hero': () =>
    import('./stats-big-number-hero-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'stats-cards-trend': () =>
    import('./stats-cards-trend-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'stats-comparison-grid': () =>
    import('./stats-comparison-grid-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'stats-dark-gradient': () =>
    import('./stats-dark-gradient-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'stats-dashboard-summary': () =>
    import('./stats-dashboard-summary-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'stats-goal-progress': () =>
    import('./stats-goal-progress-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'stats-icon-tiles': () =>
    import('./stats-icon-tiles-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'stats-kpi-row': () =>
    import('./stats-kpi-row-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'stats-progress-rings': () =>
    import('./stats-progress-rings-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'stats-with-sparklines': () =>
    import('./stats-with-sparklines-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'table-basic-striped': () =>
    import('./table-basic-striped-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'table-data-toolbar': () =>
    import('./table-data-toolbar-preview').then((m) => ({ Component: m.default, minHeight: 290 })),
  'table-editable-cells': () =>
    import('./table-editable-cells-preview').then((m) => ({ Component: m.default })),
  'table-expandable-rows': () =>
    import('./table-expandable-rows-preview').then((m) => ({ Component: m.default, minHeight: 230 })),
  'table-pagination-footer': () =>
    import('./table-pagination-footer-preview').then((m) => ({ Component: m.default, minHeight: 270 })),
  'table-responsive-stacked': () =>
    import('./table-responsive-stacked-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'table-selectable-rows': () =>
    import('./table-selectable-rows-preview').then((m) => ({ Component: m.default, minHeight: 210 })),
  'table-sortable-header': () =>
    import('./table-sortable-header-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'table-sticky-header': () =>
    import('./table-sticky-header-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'table-with-avatars-status': () =>
    import('./table-with-avatars-status-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'team-carousel-strip': () =>
    import('./team-carousel-strip-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'team-circular-avatars': () =>
    import('./team-circular-avatars-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'team-grid-cards': () =>
    import('./team-grid-cards-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'team-hiring-cta': () =>
    import('./team-hiring-cta-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'team-hover-overlay': () =>
    import('./team-hover-overlay-preview').then((m) => ({ Component: m.default, minHeight: 640 })),
  'team-leadership-featured': () =>
    import('./team-leadership-featured-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'team-list-rows': () =>
    import('./team-list-rows-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'team-minimal-names': () =>
    import('./team-minimal-names-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'team-org-columns': () =>
    import('./team-org-columns-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'team-with-social-links': () =>
    import('./team-with-social-links-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'about-awards-logos': () =>
    import('./about-awards-logos-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'about-cta-join': () =>
    import('./about-cta-join-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'about-culture-values-grid': () =>
    import('./about-culture-values-grid-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'about-founder-note': () =>
    import('./about-founder-note-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'about-image-story': () =>
    import('./about-image-story-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'about-milestones-counter': () =>
    import('./about-milestones-counter-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'about-mission-vision': () =>
    import('./about-mission-vision-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'about-process-steps': () =>
    import('./about-process-steps-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'about-quote-highlight': () =>
    import('./about-quote-highlight-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'about-two-column-intro': () =>
    import('./about-two-column-intro-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'bento-app-preview': () =>
    import('./bento-app-preview-preview').then((m) => ({ Component: m.default, minHeight: 540 })),
  'bento-dark-glass': () =>
    import('./bento-dark-glass-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'bento-features-3x2': () =>
    import('./bento-features-3x2-preview').then((m) => ({ Component: m.default, minHeight: 720 })),
  'bento-gradient-tiles': () =>
    import('./bento-gradient-tiles-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'bento-icon-features': () =>
    import('./bento-icon-features-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'bento-image-collage': () =>
    import('./bento-image-collage-preview').then((m) => ({ Component: m.default, minHeight: 760 })),
  'bento-portfolio-masonry': () =>
    import('./bento-portfolio-masonry-preview').then((m) => ({ Component: m.default, minHeight: 600 })),
  'bento-product-showcase': () =>
    import('./bento-product-showcase-preview').then((m) => ({ Component: m.default, minHeight: 740 })),
  'bento-stats-mixed': () =>
    import('./bento-stats-mixed-preview').then((m) => ({ Component: m.default, minHeight: 500 })),
  'bento-testimonial-mix': () =>
    import('./bento-testimonial-mix-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'error-403-forbidden': () =>
    import('./error-403-forbidden-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'error-404-centered': () =>
    import('./error-404-centered-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'error-404-illustration': () =>
    import('./error-404-illustration-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'error-500-server': () =>
    import('./error-500-server-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'error-empty-state': () =>
    import('./error-empty-state-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'error-maintenance': () =>
    import('./error-maintenance-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'error-offline': () =>
    import('./error-offline-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'error-rate-limited': () =>
    import('./error-rate-limited-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'error-search-no-results': () =>
    import('./error-search-no-results-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'error-with-search-box': () =>
    import('./error-with-search-box-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'globe-connections-arcs': () =>
    import('./globe-connections-arcs-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'globe-cta-band': () =>
    import('./globe-cta-band-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'globe-dark-glow': () =>
    import('./globe-dark-glow-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'globe-dotted-rotating': () =>
    import('./globe-dotted-rotating-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'globe-flat-world-dots': () =>
    import('./globe-flat-world-dots-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'globe-hero-split': () =>
    import('./globe-hero-split-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'globe-network-nodes': () =>
    import('./globe-network-nodes-preview').then((m) => ({ Component: m.default, minHeight: 370 })),
  'globe-orbit-rings': () =>
    import('./globe-orbit-rings-preview').then((m) => ({ Component: m.default, minHeight: 370 })),
  'globe-stats-overlay': () =>
    import('./globe-stats-overlay-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'globe-wireframe-sphere': () =>
    import('./globe-wireframe-sphere-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'social-counters': () =>
    import('./social-counters-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'social-feed-cards': () =>
    import('./social-feed-cards-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'social-follow-card': () =>
    import('./social-follow-card-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'social-icon-grid': () =>
    import('./social-icon-grid-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'social-links-bar': () =>
    import('./social-links-bar-preview').then((m) => ({ Component: m.default })),
  'social-profile-header': () =>
    import('./social-profile-header-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'social-proof-strip': () =>
    import('./social-proof-strip-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'social-share-buttons': () =>
    import('./social-share-buttons-preview').then((m) => ({ Component: m.default })),
  'social-share-floating': () =>
    import('./social-share-floating-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'social-testimonial-tweet': () =>
    import('./social-testimonial-tweet-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'animated-checkmark-draw': () =>
    import('./animated-checkmark-draw-preview').then((m) => ({ Component: m.default })),
  'animated-hamburger': () =>
    import('./animated-hamburger-preview').then((m) => ({ Component: m.default })),
  'blob-morph': () =>
    import('./blob-morph-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'bounce-in-entrance': () =>
    import('./bounce-in-entrance-preview').then((m) => ({ Component: m.default })),
  'card-tilt-3d': () =>
    import('./card-tilt-3d-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'confetti-burst': () =>
    import('./confetti-burst-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'flip-card-3d': () =>
    import('./flip-card-3d-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'glitch-text': () =>
    import('./glitch-text-preview').then((m) => ({ Component: m.default })),
  'gradient-border-rotate': () =>
    import('./gradient-border-rotate-preview').then((m) => ({ Component: m.default })),
  'gradient-text-animated': () =>
    import('./gradient-text-animated-preview').then((m) => ({ Component: m.default })),
  'hover-lift-card': () =>
    import('./hover-lift-card-preview').then((m) => ({ Component: m.default })),
  'hover-underline-grow': () =>
    import('./hover-underline-grow-preview').then((m) => ({ Component: m.default })),
  'parallax-layers': () =>
    import('./parallax-layers-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'pulse-attention': () =>
    import('./pulse-attention-preview').then((m) => ({ Component: m.default })),
  'ripple-effect-button': () =>
    import('./ripple-effect-button-preview').then((m) => ({ Component: m.default })),
  'scroll-reveal-slide': () =>
    import('./scroll-reveal-slide-preview').then((m) => ({ Component: m.default })),
  'text-scramble': () =>
    import('./text-scramble-preview').then((m) => ({ Component: m.default })),
  'wave-text': () =>
    import('./wave-text-preview').then((m) => ({ Component: m.default })),
  'alert-cookie-consent': () =>
    import('./alert-cookie-consent-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'alert-countdown': () =>
    import('./alert-countdown-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'alert-expandable-details': () =>
    import('./alert-expandable-details-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'alert-outline': () =>
    import('./alert-outline-preview').then((m) => ({ Component: m.default })),
  'alert-progress-timed': () =>
    import('./alert-progress-timed-preview').then((m) => ({ Component: m.default, minHeight: 200 })),
  'alert-soft-tint': () =>
    import('./alert-soft-tint-preview').then((m) => ({ Component: m.default })),
  'alert-stacked-group': () =>
    import('./alert-stacked-group-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'alert-success-solid': () =>
    import('./alert-success-solid-preview').then((m) => ({ Component: m.default })),
  'alert-system-status': () =>
    import('./alert-system-status-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'alert-with-icon-list': () =>
    import('./alert-with-icon-list-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'cart-drawer-side': () =>
    import('./cart-drawer-side-preview').then((m) => ({ Component: m.default, minHeight: 500 })),
  'cart-empty-state': () =>
    import('./cart-empty-state-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'cart-full-page': () =>
    import('./cart-full-page-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'cart-line-items': () =>
    import('./cart-line-items-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'cart-mini-dropdown': () =>
    import('./cart-mini-dropdown-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'cart-promo-code': () =>
    import('./cart-promo-code-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'cart-quantity-steppers': () =>
    import('./cart-quantity-steppers-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'cart-saved-for-later': () =>
    import('./cart-saved-for-later-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'cart-sticky-summary': () =>
    import('./cart-sticky-summary-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'cart-with-summary': () =>
    import('./cart-with-summary-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'change-password-2fa': () =>
    import('./change-password-2fa-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'change-password-basic': () =>
    import('./change-password-basic-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'change-password-card': () =>
    import('./change-password-card-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'change-password-inline': () =>
    import('./change-password-inline-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'change-password-minimal': () =>
    import('./change-password-minimal-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'change-password-modal': () =>
    import('./change-password-modal-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'change-password-split': () =>
    import('./change-password-split-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'change-password-success-state': () =>
    import('./change-password-success-state-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'change-password-with-requirements': () =>
    import('./change-password-with-requirements-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'change-password-with-strength': () =>
    import('./change-password-with-strength-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'checkout-express-buttons': () =>
    import('./checkout-express-buttons-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'checkout-gift-options': () =>
    import('./checkout-gift-options-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'checkout-guest-form': () =>
    import('./checkout-guest-form-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'checkout-multi-step': () =>
    import('./checkout-multi-step-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'checkout-order-summary': () =>
    import('./checkout-order-summary-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'checkout-payment-form': () =>
    import('./checkout-payment-form-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'checkout-review-confirm': () =>
    import('./checkout-review-confirm-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'checkout-shipping-address': () =>
    import('./checkout-shipping-address-preview').then((m) => ({ Component: m.default, minHeight: 600 })),
  'checkout-single-page': () =>
    import('./checkout-single-page-preview').then((m) => ({ Component: m.default, minHeight: 700 })),
  'checkout-two-column': () =>
    import('./checkout-two-column-preview').then((m) => ({ Component: m.default, minHeight: 560 })),
  'contact-boxed-card': () =>
    import('./contact-boxed-card-preview').then((m) => ({ Component: m.default, minHeight: 500 })),
  'contact-faq-combined': () =>
    import('./contact-faq-combined-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'contact-form-simple': () =>
    import('./contact-form-simple-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'contact-gradient-side': () =>
    import('./contact-gradient-side-preview').then((m) => ({ Component: m.default, minHeight: 660 })),
  'contact-minimal': () =>
    import('./contact-minimal-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'contact-social-links': () =>
    import('./contact-social-links-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'contact-split-map': () =>
    import('./contact-split-map-preview').then((m) => ({ Component: m.default, minHeight: 720 })),
  'contact-support-options': () =>
    import('./contact-support-options-preview').then((m) => ({ Component: m.default, minHeight: 640 })),
  'contact-two-column': () =>
    import('./contact-two-column-preview').then((m) => ({ Component: m.default, minHeight: 620 })),
  'contact-with-details': () =>
    import('./contact-with-details-preview').then((m) => ({ Component: m.default, minHeight: 640 })),
  'reset-password-card': () =>
    import('./reset-password-card-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'reset-password-expired-link': () =>
    import('./reset-password-expired-link-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'reset-password-link-sent': () =>
    import('./reset-password-link-sent-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'reset-password-minimal': () =>
    import('./reset-password-minimal-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'reset-password-new-password': () =>
    import('./reset-password-new-password-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'reset-password-otp-code': () =>
    import('./reset-password-otp-code-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'reset-password-request-email': () =>
    import('./reset-password-request-email-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'reset-password-split': () =>
    import('./reset-password-split-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'reset-password-success': () =>
    import('./reset-password-success-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'reset-password-with-strength': () =>
    import('./reset-password-with-strength-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'carousel-cards-peek': () =>
    import('./carousel-cards-peek-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'carousel-center-mode': () =>
    import('./carousel-center-mode-preview').then((m) => ({ Component: m.default, minHeight: 224 })),
  'carousel-fullscreen-hero': () =>
    import('./carousel-fullscreen-hero-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'carousel-logo-strip': () =>
    import('./carousel-logo-strip-preview').then((m) => ({ Component: m.default, minHeight: 96 })),
  'carousel-parallax': () =>
    import('./carousel-parallax-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'carousel-progress-dots': () =>
    import('./carousel-progress-dots-preview').then((m) => ({ Component: m.default })),
  'carousel-scroll-snap': () =>
    import('./carousel-scroll-snap-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'carousel-testimonial': () =>
    import('./carousel-testimonial-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'carousel-thumbnail-sync': () =>
    import('./carousel-thumbnail-sync-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'carousel-vertical': () =>
    import('./carousel-vertical-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'comparison-checkmark-grid': () =>
    import('./comparison-checkmark-grid-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'comparison-highlight-diff': () =>
    import('./comparison-highlight-diff-preview').then((m) => ({ Component: m.default, minHeight: 360 })),
  'comparison-plan-matrix': () =>
    import('./comparison-plan-matrix-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'comparison-pricing-toggle': () =>
    import('./comparison-pricing-toggle-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'comparison-pros-cons': () =>
    import('./comparison-pros-cons-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'comparison-side-by-side-cards': () =>
    import('./comparison-side-by-side-cards-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'comparison-spec-list': () =>
    import('./comparison-spec-list-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'comparison-three-column': () =>
    import('./comparison-three-column-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'comparison-tiered-features': () =>
    import('./comparison-tiered-features-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'comparison-vs-versus': () =>
    import('./comparison-vs-versus-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'dock-app-launcher': () =>
    import('./dock-app-launcher-preview').then((m) => ({ Component: m.default })),
  'dock-command-strip': () =>
    import('./dock-command-strip-preview').then((m) => ({ Component: m.default })),
  'dock-floating-actions': () =>
    import('./dock-floating-actions-preview').then((m) => ({ Component: m.default })),
  'dock-glass-blur': () =>
    import('./dock-glass-blur-preview').then((m) => ({ Component: m.default })),
  'dock-icon-tooltips': () =>
    import('./dock-icon-tooltips-preview').then((m) => ({ Component: m.default })),
  'dock-mini-player': () =>
    import('./dock-mini-player-preview').then((m) => ({ Component: m.default })),
  'dock-notification-badges': () =>
    import('./dock-notification-badges-preview').then((m) => ({ Component: m.default })),
  'dock-segmented': () =>
    import('./dock-segmented-preview').then((m) => ({ Component: m.default })),
  'dock-side-collapsible': () =>
    import('./dock-side-collapsible-preview').then((m) => ({ Component: m.default })),
  'dock-tab-bar': () =>
    import('./dock-tab-bar-preview').then((m) => ({ Component: m.default })),
  'dropdown-account-switch': () =>
    import('./dropdown-account-switch-preview').then((m) => ({ Component: m.default })),
  'dropdown-checkbox-multi': () =>
    import('./dropdown-checkbox-multi-preview').then((m) => ({ Component: m.default })),
  'dropdown-color-swatches': () =>
    import('./dropdown-color-swatches-preview').then((m) => ({ Component: m.default })),
  'dropdown-command': () =>
    import('./dropdown-command-preview').then((m) => ({ Component: m.default })),
  'dropdown-mega': () =>
    import('./dropdown-mega-preview').then((m) => ({ Component: m.default })),
  'dropdown-multi-column': () =>
    import('./dropdown-multi-column-preview').then((m) => ({ Component: m.default })),
  'dropdown-notification': () =>
    import('./dropdown-notification-preview').then((m) => ({ Component: m.default })),
  'dropdown-radio-single': () =>
    import('./dropdown-radio-single-preview').then((m) => ({ Component: m.default })),
  'dropdown-search-filter': () =>
    import('./dropdown-search-filter-preview').then((m) => ({ Component: m.default })),
  'dropdown-split-button': () =>
    import('./dropdown-split-button-preview').then((m) => ({ Component: m.default })),
  'fab-badge-count': () =>
    import('./fab-badge-count-preview').then((m) => ({ Component: m.default })),
  'fab-bottom-sheet-trigger': () =>
    import('./fab-bottom-sheet-trigger-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'fab-chat-bubble': () =>
    import('./fab-chat-bubble-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'fab-draggable-visual': () =>
    import('./fab-draggable-visual-preview').then((m) => ({ Component: m.default, minHeight: 256 })),
  'fab-labeled-pill': () =>
    import('./fab-labeled-pill-preview').then((m) => ({ Component: m.default })),
  'fab-menu-radial': () =>
    import('./fab-menu-radial-preview').then((m) => ({ Component: m.default, minHeight: 256 })),
  'fab-mini': () =>
    import('./fab-mini-preview').then((m) => ({ Component: m.default })),
  'fab-morphing': () =>
    import('./fab-morphing-preview').then((m) => ({ Component: m.default })),
  'fab-multi-action-list': () =>
    import('./fab-multi-action-list-preview').then((m) => ({ Component: m.default, minHeight: 288 })),
  'fab-progress-ring': () =>
    import('./fab-progress-ring-preview').then((m) => ({ Component: m.default })),
  'gallery-carousel-fullwidth': () =>
    import('./gallery-carousel-fullwidth-preview').then((m) => ({ Component: m.default })),
  'gallery-horizontal-scroll': () =>
    import('./gallery-horizontal-scroll-preview').then((m) => ({ Component: m.default })),
  'gallery-hover-zoom': () =>
    import('./gallery-hover-zoom-preview').then((m) => ({ Component: m.default })),
  'gallery-instagram-grid': () =>
    import('./gallery-instagram-grid-preview').then((m) => ({ Component: m.default })),
  'gallery-justified': () =>
    import('./gallery-justified-preview').then((m) => ({ Component: m.default })),
  'gallery-load-more': () =>
    import('./gallery-load-more-preview').then((m) => ({ Component: m.default })),
  'gallery-masonry-captions': () =>
    import('./gallery-masonry-captions-preview').then((m) => ({ Component: m.default })),
  'gallery-polaroid': () =>
    import('./gallery-polaroid-preview').then((m) => ({ Component: m.default })),
  'gallery-tabs-category': () =>
    import('./gallery-tabs-category-preview').then((m) => ({ Component: m.default })),
  'gallery-video-thumbs': () =>
    import('./gallery-video-thumbs-preview').then((m) => ({ Component: m.default })),
  'marketing-announcement-bar': () =>
    import('./marketing-announcement-bar-preview').then((m) => ({ Component: m.default })),
  'marketing-countdown-offer': () =>
    import('./marketing-countdown-offer-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'marketing-feature-highlight': () =>
    import('./marketing-feature-highlight-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'marketing-lead-magnet': () =>
    import('./marketing-lead-magnet-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'marketing-logos-social-proof': () =>
    import('./marketing-logos-social-proof-preview').then((m) => ({ Component: m.default, minHeight: 220 })),
  'marketing-promo-banner': () =>
    import('./marketing-promo-banner-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'marketing-referral-card': () =>
    import('./marketing-referral-card-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'marketing-stats-band': () =>
    import('./marketing-stats-band-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'marketing-value-props': () =>
    import('./marketing-value-props-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'marketing-webinar-signup': () =>
    import('./marketing-webinar-signup-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'modal-alert-warning': () =>
    import('./modal-alert-warning-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'modal-command-palette': () =>
    import('./modal-command-palette-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'modal-cookie': () =>
    import('./modal-cookie-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'modal-image-lightbox': () =>
    import('./modal-image-lightbox-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'modal-onboarding-steps': () =>
    import('./modal-onboarding-steps-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'modal-scrollable-terms': () =>
    import('./modal-scrollable-terms-preview').then((m) => ({ Component: m.default, minHeight: 460 })),
  'modal-side-panel': () =>
    import('./modal-side-panel-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'modal-stacked': () =>
    import('./modal-stacked-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'modal-success': () =>
    import('./modal-success-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'modal-video': () =>
    import('./modal-video-preview').then((m) => ({ Component: m.default, minHeight: 420 })),
  'notification-banner-gradient': () =>
    import('./notification-banner-gradient-preview').then((m) => ({ Component: m.default })),
  'notification-empty-state': () =>
    import('./notification-empty-state-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'notification-grouped': () =>
    import('./notification-grouped-preview').then((m) => ({ Component: m.default })),
  'notification-in-app-feed': () =>
    import('./notification-in-app-feed-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'notification-permission-prompt': () =>
    import('./notification-permission-prompt-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'notification-settings-list': () =>
    import('./notification-settings-list-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'notification-snackbar-action': () =>
    import('./notification-snackbar-action-preview').then((m) => ({ Component: m.default })),
  'notification-toast-progress': () =>
    import('./notification-toast-progress-preview').then((m) => ({ Component: m.default })),
  'notification-toast-success': () =>
    import('./notification-toast-success-preview').then((m) => ({ Component: m.default })),
  'notification-with-avatar': () =>
    import('./notification-with-avatar-preview').then((m) => ({ Component: m.default })),
  'pagination-arrows-only': () =>
    import('./pagination-arrows-only-preview').then((m) => ({ Component: m.default })),
  'pagination-bordered': () =>
    import('./pagination-bordered-preview').then((m) => ({ Component: m.default })),
  'pagination-compact-dots': () =>
    import('./pagination-compact-dots-preview').then((m) => ({ Component: m.default })),
  'pagination-cursor-based': () =>
    import('./pagination-cursor-based-preview').then((m) => ({ Component: m.default })),
  'pagination-jump-to-page': () =>
    import('./pagination-jump-to-page-preview').then((m) => ({ Component: m.default })),
  'pagination-mini': () =>
    import('./pagination-mini-preview').then((m) => ({ Component: m.default })),
  'pagination-range-info': () =>
    import('./pagination-range-info-preview').then((m) => ({ Component: m.default })),
  'pagination-rounded-pills': () =>
    import('./pagination-rounded-pills-preview').then((m) => ({ Component: m.default })),
  'pagination-simple-count': () =>
    import('./pagination-simple-count-preview').then((m) => ({ Component: m.default })),
  'pagination-table-footer': () =>
    import('./pagination-table-footer-preview').then((m) => ({ Component: m.default })),
  'popover-color-picker': () =>
    import('./popover-color-picker-preview').then((m) => ({ Component: m.default })),
  'popover-confirm': () =>
    import('./popover-confirm-preview').then((m) => ({ Component: m.default })),
  'popover-date-mini': () =>
    import('./popover-date-mini-preview').then((m) => ({ Component: m.default })),
  'popover-emoji': () =>
    import('./popover-emoji-preview').then((m) => ({ Component: m.default })),
  'popover-form': () =>
    import('./popover-form-preview').then((m) => ({ Component: m.default })),
  'popover-hover-card': () =>
    import('./popover-hover-card-preview').then((m) => ({ Component: m.default })),
  'popover-nested': () =>
    import('./popover-nested-preview').then((m) => ({ Component: m.default })),
  'popover-notification': () =>
    import('./popover-notification-preview').then((m) => ({ Component: m.default })),
  'popover-share': () =>
    import('./popover-share-preview').then((m) => ({ Component: m.default })),
  'popover-user-card': () =>
    import('./popover-user-card-preview').then((m) => ({ Component: m.default })),
  'pricing-annual-discount': () =>
    import('./pricing-annual-discount-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'pricing-enterprise-cta': () =>
    import('./pricing-enterprise-cta-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'pricing-faq-combined': () =>
    import('./pricing-faq-combined-preview').then((m) => ({ Component: m.default, minHeight: 440 })),
  'pricing-feature-table': () =>
    import('./pricing-feature-table-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'pricing-freemium': () =>
    import('./pricing-freemium-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'pricing-gradient-cards': () =>
    import('./pricing-gradient-cards-preview').then((m) => ({ Component: m.default, minHeight: 500 })),
  'pricing-highlight-popular': () =>
    import('./pricing-highlight-popular-preview').then((m) => ({ Component: m.default, minHeight: 520 })),
  'pricing-minimal': () =>
    import('./pricing-minimal-preview').then((m) => ({ Component: m.default, minHeight: 400 })),
  'pricing-per-seat': () =>
    import('./pricing-per-seat-preview').then((m) => ({ Component: m.default, minHeight: 380 })),
  'pricing-two-tier': () =>
    import('./pricing-two-tier-preview').then((m) => ({ Component: m.default, minHeight: 480 })),
  'sidebar-badges-counts': () =>
    import('./sidebar-badges-counts-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'sidebar-dark-theme': () =>
    import('./sidebar-dark-theme-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'sidebar-floating-card': () =>
    import('./sidebar-floating-card-preview').then((m) => ({ Component: m.default, minHeight: 280 })),
  'sidebar-gradient-brand': () =>
    import('./sidebar-gradient-brand-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'sidebar-mini-expandable': () =>
    import('./sidebar-mini-expandable-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'sidebar-search-nav': () =>
    import('./sidebar-search-nav-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'sidebar-sections-labeled': () =>
    import('./sidebar-sections-labeled-preview').then((m) => ({ Component: m.default, minHeight: 340 })),
  'sidebar-two-level': () =>
    import('./sidebar-two-level-preview').then((m) => ({ Component: m.default, minHeight: 260 })),
  'sidebar-with-footer-user': () =>
    import('./sidebar-with-footer-user-preview').then((m) => ({ Component: m.default, minHeight: 320 })),
  'sidebar-workspace-switcher': () =>
    import('./sidebar-workspace-switcher-preview').then((m) => ({ Component: m.default, minHeight: 300 })),
  'tabs-animated-indicator': () =>
    import('./tabs-animated-indicator-preview').then((m) => ({ Component: m.default })),
  'tabs-card-panels': () =>
    import('./tabs-card-panels-preview').then((m) => ({ Component: m.default })),
  'tabs-closable': () =>
    import('./tabs-closable-preview').then((m) => ({ Component: m.default })),
  'tabs-full-width': () =>
    import('./tabs-full-width-preview').then((m) => ({ Component: m.default })),
  'tabs-icon-only': () =>
    import('./tabs-icon-only-preview').then((m) => ({ Component: m.default })),
  'tabs-nested': () =>
    import('./tabs-nested-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
  'tabs-scrollable': () =>
    import('./tabs-scrollable-preview').then((m) => ({ Component: m.default })),
  'tabs-segmented': () =>
    import('./tabs-segmented-preview').then((m) => ({ Component: m.default })),
  'tabs-with-badges': () =>
    import('./tabs-with-badges-preview').then((m) => ({ Component: m.default })),
  'tabs-with-dropdown-overflow': () =>
    import('./tabs-with-dropdown-overflow-preview').then((m) => ({ Component: m.default, minHeight: 240 })),
};

export function hasPreview(slug: string): boolean {
  return slug in PREVIEWS;
}
