/**
 * Email signature model. The output is table-based, inline-styled HTML (the only
 * thing Gmail/Outlook/Apple Mail render reliably), generated by `build.ts` from
 * this data plus a theme. No external assets: images are data-URLs the user
 * uploads, and social icons are self-contained colored chips.
 */

export const SOCIAL_PLATFORMS = [
  'facebook',
  'linkedin',
  'instagram',
  'x',
  'youtube',
  'github',
  'behance',
  'dribbble',
] as const;
export type SocialPlatform = (typeof SOCIAL_PLATFORMS)[number];

export interface SocialLink {
  platform: SocialPlatform;
  url: string;
}

export interface SignatureDesign {
  /** CSS font-family stack (email-safe web-safe fonts). */
  font: string;
  primaryColor: string;
  textColor: string;
  mutedColor: string;
  accentColor: string;
  background: string;
  iconSize: number;
  roundedImages: boolean;
  showBorder: boolean;
  showDividers: boolean;
  /** Vertical gap between blocks, px. */
  spacing: number;
  photoSize: number;
  logoWidth: number;
}

export interface SignatureData {
  name: string;
  designation: string;
  company: string;
  phone: string;
  mobile: string;
  email: string;
  website: string;
  address: string;
  /** Data-URLs, or empty. */
  logo: string;
  photo: string;
  banner: string;
  cta: { label: string; url: string };
  socials: SocialLink[];
  themeId: string;
  design: SignatureDesign;
}
