/**
 * Emit the CSS half of the published package. Runs after `tsc`.
 *
 * Three artefacts, three audiences:
 *
 *   dist/tokens.css   the design tokens, copied from `@adysre/theme` so the
 *                     published package carries no workspace dependency.
 *   dist/styles.css   the Tailwind v4 entry a consumer imports. Same job as
 *                     `src/styles.css` but self-contained: it imports the copied
 *                     tokens and `@source`s the compiled `dist` next to it.
 *   dist/adysre.css   every utility our components use, pre-compiled, for
 *                     consumers who do not run Tailwind at all.
 *
 * The tokens are copied rather than duplicated in source: `packages/theme` stays
 * the single place a colour is ever defined.
 */

import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, '..');
const DIST = join(PKG, 'dist');
const THEME_TOKENS = join(PKG, '..', 'theme', 'src', 'tokens.css');

/** The `dark:` variant our components rely on, declared once for every artefact. */
const DARK_VARIANT = '@custom-variant dark (&:where(.dark, .dark *));';

const PUBLISHED_STYLES = `/*
 * adysre — Tailwind v4 entry.
 *
 *   @import "tailwindcss";
 *   @import "adysre/styles.css";
 *
 * Brings the ADYSRE design tokens and points Tailwind at this package's files,
 * so the utility classes inside our components are generated in your build.
 *
 * Generated by scripts/build-assets.mjs — edit src/styles.css, not this file.
 */

@import './tokens.css';

@source './';

${DARK_VARIANT}
`;

function copyTokens() {
  copyFileSync(THEME_TOKENS, join(DIST, 'tokens.css'));
}

function writeStyles() {
  writeFileSync(join(DIST, 'styles.css'), PUBLISHED_STYLES, 'utf8');
}

/**
 * Compile the standalone stylesheet.
 *
 * Scanning `dist` (the emitted JS) rather than `src` is deliberate: it is
 * exactly what a consumer's Tailwind would scan, so the prebuilt file and the
 * Tailwind-native path can never disagree about which utilities exist.
 */
function buildStandaloneCss() {
  const tmp = mkdtempSync(join(tmpdir(), 'adysre-css-'));
  const entry = join(tmp, 'entry.css');
  writeFileSync(
    entry,
    [
      `@import 'tailwindcss';`,
      `@import '${join(DIST, 'tokens.css')}';`,
      `@source '${DIST}';`,
      DARK_VARIANT,
      '',
    ].join('\n'),
    'utf8',
  );

  try {
    execFileSync(
      'pnpm',
      ['exec', 'tailwindcss', '--input', entry, '--output', join(DIST, 'adysre.css'), '--minify'],
      { cwd: PKG, stdio: 'inherit' },
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

/**
 * Rewrite `./x.ts` / `./x.tsx` to `./x.js` in the emitted declarations.
 *
 * `rewriteRelativeImportExtensions` does this for the JavaScript but not for
 * `.d.ts` output, and a declaration pointing at `./button.tsx` resolves to
 * nothing inside `dist` — every type in the package would come back `any` for
 * consumers. Narrow by construction: relative specifiers only, never bare
 * package names, and the JS is asserted untouched by `verifyEsm` below.
 */
function fixDeclarationExtensions() {
  const RELATIVE_TS = /(from\s*|import\(\s*)(['"])(\.\.?\/[^'"]*?)\.tsx?\2/g;
  let touched = 0;

  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name.endsWith('.d.ts')) {
        const before = readFileSync(full, 'utf8');
        const after = before.replace(RELATIVE_TS, '$1$2$3.js$2');
        if (after !== before) {
          writeFileSync(full, after, 'utf8');
          touched++;
        }
      }
    }
  };

  walk(DIST);
  return touched;
}

/**
 * Fail the build rather than publish something that cannot be imported.
 *
 * A relative specifier that still carries a TypeScript extension means the emit
 * pipeline changed under us; better to break here than to ship a package whose
 * every deep import 404s at the consumer's bundler.
 */
function verifyEsm() {
  const BAD = /(from\s*|import\(\s*)['"]\.\.?\/[^'"]*?\.tsx?['"]/;
  const offenders = [];

  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.js') || entry.name.endsWith('.d.ts')) {
        if (BAD.test(readFileSync(full, 'utf8'))) offenders.push(full);
      }
    }
  };

  walk(DIST);
  if (offenders.length) {
    throw new Error(
      `build-assets: ${offenders.length} emitted file(s) still import TypeScript extensions, e.g. ${offenders[0]}`,
    );
  }
}

copyTokens();
writeStyles();
const fixed = fixDeclarationExtensions();
verifyEsm();
buildStandaloneCss();
console.log(
  `build-assets: dist/tokens.css, dist/styles.css, dist/adysre.css (${fixed} declaration files rewritten)`,
);
