/**
 * Generate one React component per icon from the raw catalogue.
 *
 * AUTHORING MODEL: `src/icons/data.ts` is the source of truth - an icon is a
 * name, a category, tags and an SVG body. This script bakes each body into a
 * standalone `.tsx` so consumers can `import { ArrowUpRight } from 'adysre/icons'`
 * and have the bundler drop the other 447.
 *
 * Nothing here is hand-editable: `src/icons/generated/` is wiped and rewritten
 * on every run. Add an icon to `data.ts`, then `pnpm --filter adysre gen:icons`.
 *
 * The JSX attribute mapping is imported from `svg.ts` rather than re-implemented,
 * so the generated components and the site's copy-paste export can never drift.
 */

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { RAW_ICONS } from '../src/icons/data.ts';
import { pascalCase, toJsxAttrs } from '../src/icons/svg.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, '..', 'src', 'icons', 'generated');

const BANNER = `/* AUTO-GENERATED by scripts/generate-icons.ts. Do not edit - edit src/icons/data.ts. */`;

/** `arrow-up-right` -> `arrow-up-right.tsx`, matching the repo's kebab-case file rule. */
function fileNameFor(name: string): string {
  return `${name}.tsx`;
}

function componentSource(name: string, body: string): string {
  const comp = pascalCase(name);
  const jsx = toJsxAttrs(body.trim()).replace(/></g, '>\n      <');
  return `${BANNER}
import type { IconProps } from '../types.ts';

export function ${comp}({
  size = 24,
  color = 'currentColor',
  strokeWidth = 1.5,
  ...props
}: IconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden={props['aria-label'] ? undefined : true}
      {...props}
    >
      ${jsx}
    </svg>
  );
}
`;
}

function main(): void {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  // `data.ts` may carry duplicates across categories; the catalogue de-dupes by
  // name, so the generator must too or two files would fight over one export.
  const seen = new Set<string>();
  const emitted: { name: string; comp: string }[] = [];

  for (const icon of RAW_ICONS) {
    if (seen.has(icon.name)) continue;
    seen.add(icon.name);
    writeFileSync(join(OUT_DIR, fileNameFor(icon.name)), componentSource(icon.name, icon.body), 'utf8');
    emitted.push({ name: icon.name, comp: pascalCase(icon.name) });
  }

  emitted.sort((a, b) => a.comp.localeCompare(b.comp));

  // Two components can pascal-case to the same identifier (`close-x` vs `close_x`).
  // Fail loudly rather than emit a barrel that silently shadows one of them.
  const byComp = new Map<string, string>();
  for (const e of emitted) {
    const clash = byComp.get(e.comp);
    if (clash) throw new Error(`Icon name collision: "${clash}" and "${e.name}" both export ${e.comp}`);
    byComp.set(e.comp, e.name);
  }

  const barrel = [
    BANNER,
    ...emitted.map((e) => `export { ${e.comp} } from './${e.name}.tsx';`),
    '',
  ].join('\n');
  writeFileSync(join(OUT_DIR, 'index.ts'), barrel, 'utf8');

  console.log(`generate-icons: ${emitted.length} icon components -> src/icons/generated/`);
}

main();
