/**
 * ADYSRE API Studio - identifiers.
 *
 * Ids are UUIDv7: a 48-bit millisecond timestamp, then a 12-bit counter, then
 * random bits. Two properties matter here.
 *
 * They are generated by the CLIENT, because a request, a tab and its draft all
 * need an identity the moment they are typed, long before anything is saved.
 * And they SORT BY CREATION TIME, which is what keeps them usable as database
 * primary keys: random v4 keys scatter inserts across a B-tree and fragment it,
 * while time-ordered keys append (DATABASE_ARCHITECTURE.md asks for UUIDv7).
 *
 * The counter is what makes ids created inside the same millisecond still
 * ordered. If it overflows (more than 4096 ids in one millisecond) the
 * generator borrows from the next millisecond rather than repeating itself, and
 * a clock that steps backwards is ignored for the same reason.
 */

const VERSION_7 = 0x70;
const VARIANT_RFC = 0x80;
const COUNTER_MASK = 0xfff;

let lastMs = 0;
let counter = 0;

/** Hex table, so formatting an id is 16 lookups rather than 16 conversions. */
const HEX: string[] = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, '0'));

/**
 * Generate a UUIDv7.
 *
 * @returns a lowercase, dash-separated UUID whose version nibble is 7.
 */
export function createId(): string {
  const now = Date.now();

  if (now > lastMs) {
    lastMs = now;
    counter = 0;
  } else {
    // Same millisecond, or a clock that went backwards: keep counting forward.
    counter += 1;
    if (counter > COUNTER_MASK) {
      lastMs += 1;
      counter = 0;
    }
  }

  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes.subarray(8));

  const ms = lastMs;
  // 48-bit timestamp, big-endian. The high 16 bits need floating-point maths:
  // a millisecond timestamp exceeds what bitwise operators can hold.
  bytes[0] = Math.floor(ms / 2 ** 40) & 0xff;
  bytes[1] = Math.floor(ms / 2 ** 32) & 0xff;
  bytes[2] = (ms >>> 24) & 0xff;
  bytes[3] = (ms >>> 16) & 0xff;
  bytes[4] = (ms >>> 8) & 0xff;
  bytes[5] = ms & 0xff;
  bytes[6] = VERSION_7 | ((counter >> 8) & 0x0f);
  bytes[7] = counter & 0xff;
  bytes[8] = (bytes[8]! & 0x3f) | VARIANT_RFC;

  return (
    HEX[bytes[0]!]! + HEX[bytes[1]!]! + HEX[bytes[2]!]! + HEX[bytes[3]!]! + '-' +
    HEX[bytes[4]!]! + HEX[bytes[5]!]! + '-' +
    HEX[bytes[6]!]! + HEX[bytes[7]!]! + '-' +
    HEX[bytes[8]!]! + HEX[bytes[9]!]! + '-' +
    HEX[bytes[10]!]! + HEX[bytes[11]!]! + HEX[bytes[12]!]! +
    HEX[bytes[13]!]! + HEX[bytes[14]!]! + HEX[bytes[15]!]!
  );
}

/** The millisecond a UUIDv7 was generated in, or `null` if it is not a v7. */
export function timestampOf(id: string): number | null {
  const hex = id.replace(/-/g, '');
  if (hex.length !== 32 || hex[12] !== '7') return null;
  const ms = Number.parseInt(hex.slice(0, 12), 16);
  return Number.isNaN(ms) ? null : ms;
}
