import type { ScanRecord } from '../history/types';
import type { Finding, ScanResult, WebVitals } from '../types';

/**
 * Markdown export - a human-readable report you can paste into a PR, an issue
 * or a doc. Pure: a record in, a Markdown string out.
 */

function scoresTable(result: ScanResult): string {
  const rows = result.categories
    .map((c) => `| ${c.category} | ${c.score} |`)
    .join('\n');
  return `| Category | Score |\n| --- | --- |\n${rows}`;
}

function vitalsTable(vitals: WebVitals): string {
  const rows: Array<[string, number | undefined, string]> = [
    ['LCP', vitals.lcp, ' ms'],
    ['INP', vitals.inp, ' ms'],
    ['CLS', vitals.cls, ''],
    ['FCP', vitals.fcp, ' ms'],
    ['TBT', vitals.tbt, ' ms'],
    ['TTFB', vitals.ttfb, ' ms'],
  ];
  const present = rows.filter((r): r is [string, number, string] => r[1] != null);
  if (present.length === 0) return '';
  const body = present.map(([label, value, unit]) => `| ${label} | ${value}${unit} |`).join('\n');
  return `\n## Core Web Vitals\n\n| Metric | Value |\n| --- | --- |\n${body}\n`;
}

function findingBlock(finding: Finding): string {
  const lines = [
    `### ${finding.severity.toUpperCase()} — ${finding.description}`,
    '',
    `- **Category:** ${finding.category}`,
    `- **Fix:** ${finding.fix}`,
    `- **Impact:** ${finding.impact}`,
  ];
  if (finding.estimatedSavings) lines.push(`- **Estimated saving:** ${finding.estimatedSavings}`);
  if (finding.documentation) lines.push(`- **Docs:** ${finding.documentation}`);
  return lines.join('\n');
}

export function toMarkdownReport(record: ScanRecord): string {
  const { result } = record;
  const parts: string[] = [
    '# Website Intelligence report',
    '',
    `- **URL:** ${result.finalUrl}`,
    `- **Scanned:** ${record.createdAt}`,
    `- **Overall score:** ${result.overallScore} / 100`,
    '',
    '## Scores',
    '',
    scoresTable(result),
    '',
    '## Technologies',
    '',
    result.technologies.length > 0 ? result.technologies.map((t) => `- ${t}`).join('\n') : '_None detected._',
  ];

  const vitals = result.metrics.webVitals ? vitalsTable(result.metrics.webVitals) : '';
  if (vitals) parts.push(vitals);

  parts.push('', `## Recommendations (${result.findings.length})`, '');
  if (result.findings.length === 0) {
    parts.push('_No issues found in this pass._');
  } else {
    parts.push(result.findings.map(findingBlock).join('\n\n'));
  }

  parts.push('', '---', '_Generated by ADYSRE Website Intelligence._', '');
  return parts.join('\n');
}
