import reactHooks from 'eslint-plugin-react-hooks';
import base from './base.js';

/**
 * ESLint config for framework-free React packages — today, `adysre`.
 *
 * The React Hooks plugin on top of the shared base, and deliberately NOT the
 * Next.js plugin. The published library must render identically in Next.js,
 * Vite, Remix and a downloaded starter, so its components use plain `<a>` and
 * `<img>`; the Next-specific rules that push you towards `next/link` and
 * `next/image` would be actively wrong here.
 *
 * Registering `react-hooks` matters beyond style: without it, every targeted
 * `eslint-disable-next-line react-hooks/exhaustive-deps` in the source is itself
 * an error ("Definition for rule … was not found"), which means the rule was
 * never enforced anywhere in the package.
 */
export default [
  ...base,
  {
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    // Generated by `scripts/generate-icons.ts` and `generate-blocks-barrel.ts`.
    // Fix the generator, never the output.
    ignores: ['src/icons/generated/**', 'src/blocks/index.ts'],
  },
];
