name: Deploy ADYSRE Production

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc


      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false


      - name: Verify tools
        run: |
          node -v
          pnpm -v


      - name: Install dependencies
        run: pnpm install --frozen-lockfile


      - name: Generate Prisma Client
        run: pnpm db:generate


      - name: Build ADYSRE
        run: pnpm build


      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd /home/ubuntu/Adysre

            git pull origin main

            pnpm install --frozen-lockfile

            pnpm db:generate

            pnpm build

            pm2 restart adysre-api
            pm2 restart adysre-web

            pm2 save